Remove bwcli.
I'm not using it and it's causing problems:

  Error: writing blob: adding layer with blob "sha256:9e214739ed87bf5d26f5d9701d11f41093b5f4a7723ddf67ffa9c369b3e8e2f6": ApplyLayer stdout:  stderr: potentially insufficient UIDs or GIDs available in user namespace (requested 110779:100 for /usr/local/lib/node_modules/@bitwarden/cli/node_modules/optionator/CHANGELOG.md): Check /etc/subuid and /etc/subgid if configured locally and run "podman system migrate": lchown /usr/local/lib/node_modules/@bitwarden/cli/node_modules/optionator/CHANGELOG.md: invalid argument exit status 1